infrahouse/infrahouse-core

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/dynamodb.py, src/infrahouse_core/aws/ec2_instance.py, tests/aws/dynamodb/test_lock.py, tests/aws/ec2_instance/test_ip.py
- **Add DynamoDB locks and some EC2Instance properties**
- **Add bump2version dependency**
- **Bump version: 0.1.0 → 0.2.0**
=> update dns features

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/ec2_instance.py, src/infrahouse_core/aws/route53/exceptions.py, src/infrahouse_core/aws/route53/zone.py, tests/aws/ec2_instance/test_add_tag.py, tests/aws/route53/test_zone.py
- **Add Zone class for Route53 operations**
- **Bump version: 0.3.0 → 0.4.0**
=> Add Zone class for Route53 operations

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/route53/zone.py, tests/aws/route53/test_zone.py
- **Fix list index out of range in search_hostname()**
- **Bump version: 0.4.0 → 0.4.1**
=> Fix list index out of range in search_hostname()

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/ec2_instance.py, tests/aws/ec2_instance/test_ip.py
- **.hostname should be None if not set**
- **Bump version: 0.4.1 → 0.4.2**
=> .hostname should be None if not set

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/route53/zone.py
- **Warn if a record is not found when deleting it**
- **Bump version: 0.4.2 → 0.4.3**
=> extra logging

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/asg.py, src/infrahouse_core/aws/asg_instance.py, src/infrahouse_core/aws/dynamodb.py, src/infrahouse_core/aws/ec2_instance.py
- **Add region to AWS classes**
- **Bump version: 0.4.3 → 0.5.0**
=> Add region support in AWS classes

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/asg.py
- **Fix region in ASG instances**
- **Bump version: 0.5.0 → 0.5.1**
=> Fix region in ASG instances

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/route53/zone.py, tests/aws/route53/test_zone.py
- **Emit warning when deleting unknown records**
- **Bump version: 0.5.1 → 0.5.2**
=> Emit warning when deleting unknown records

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/asg.py
- **Add record_lifecycle_action_heartbeat() method to ASG class**
- **Bump version: 0.5.2 → 0.6.0**
=> record lifecycle action heartbeat

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/ec2_instance.py, tests/aws/ec2_instance/test_add_tag.py, tests/aws/ec2_instance/test_ec2_client.py, tests/aws/route53/test_zone.py
- **Add ec2_client argument to EC2Instance**
- **Bump version: 0.6.0 → 0.7.0**
=> Add ec2_client argument to EC2Instance

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/ec2_instance.py, tests/aws/ec2_instance/test_describe_instance.py, tests/aws/ec2_instance/test_ec2_client.py
- **Fix ec2_client call**
- **Bump version: 0.7.0 → 0.7.1**
=> Fix ec2_client call

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/github.py
- **Add methods and functions for GitHub runner regsitration**
- **Bump version: 0.8.0 → 0.9.0**
=> Add methods and functions for GitHub runner registration

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/asg_instance.py
- **Add protect()/unprotect() methods to ASGInstance()**
- **Bump version: 0.9.0 → 0.10.0**
=> Add protect()/unprotect() methods to ASGInstance()

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/github.py, tests/test_github.py
- **feat: add support for GitHub Actions runner metadata via API**
- **Bump version: 0.10.0 → 0.11.0**
=> feat: add support for GitHub Actions runner metadata via API

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/timeout.py
- **Add timeout contextmanager**
- **Bump version: 0.11.0 → 0.12.0**
=> Add timeout contextmanager

.bumpversion.cfg, Makefile, docs/infrahouse_core.aws.route53.rst, docs/infrahouse_core.aws.rst, docs/infrahouse_core.rst, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/dynamodb.py, src/infrahouse_core/aws/ec2_instance.py, src/infrahouse_core/github.py, src/infrahouse_core/logging.py, tests/aws/ec2_instance/test_add_tag.py, tests/aws/ec2_instance/test_send_command.py
- **feat(ssm): add execute_command() helper for inline command execution**
- **Bump version: 0.12.0 → 0.13.0**
=> feat(ssm): add execute_command() helper for inline command execution

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/ec2_instance.py
- **Add option to pass SSM client to EC2Instance**
- **Bump version: 0.14.1 → 0.15.0**
=> Add option to pass SSM client to EC2Instance

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/github.py
- **Extend `GitHubActions.ensure_registration_token()` functionality**
- **Bump version: 0.15.0 → 0.16.0**
=> Extend `GitHubActions.ensure_registration_token()` functionality

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/asg.py, src/infrahouse_core/aws/ec2_instance.py, src/infrahouse_core/aws/route53/zone.py, tests/aws/ec2_instance/test_describe_instance.py
- **Add role_arn to ASG, EC2Instance, and Zone**
- **Bump version: 0.16.1 → 0.17.0**
=> Add role_arn to ASG, EC2Instance, and Zone

.bumpversion.cfg, pyproject.toml, src/infrahouse_core/__init__.py, src/infrahouse_core/aws/__init__.py, src/infrahouse_core/aws/asg.py, src/infrahouse_core/logging.py, tests/aws/asg/test_role.py, tests/aws/ec2_instance/test_role.py, tests/conftest.py
- **pass role to ASGInstance**
- **Bump version: 0.17.0 → 0.17.1**
- **remove dev test**
=> Fix lost role when used in ASG
